import Footer from './components/Site/Footer'
import SiteHeader from './components/Site/SiteHeader'
import './globals.css'
import {Toaster} from 'react-hot-toast'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <SiteHeader />
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  )
}
